services:
  - type: static
    name: sanhia
    buildCommand: npm run build
    publishPath: dist
    staticPublishPath: /
    routes:
      - path: /
        dest: /index.html
      - path: /*
        dest: /index.html
